version: '3.8'

services:
  app:
    image: ghcr.io/juanfeliperestrepobuitrago/herzonteis/herzon_ecommerce:latest
    container_name: herzon_app
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: herzon_postgres
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: herzon_pgadmin
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./.nginx-proxy-manager/data:/data
      - ./.nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:81"]
      interval: 1m
      timeout: 10s
      retries: 5

networks:
  app_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data: